export enum MilthmErrorCode {
  // Plugin lifecycle
  API_CLIENT_NOT_INIT = 'API_CLIENT_NOT_INIT',
  SESSION_MANAGER_NOT_INIT = 'SESSION_MANAGER_NOT_INIT',
  PLUGIN_NOT_INIT = 'PLUGIN_NOT_INIT',

  // Auth URL generation
  AUTH_GEN_HTTP_FAILED = 'AUTH_GEN_HTTP_FAILED',
  AUTH_GEN_PARSE_FAILED = 'AUTH_GEN_PARSE_FAILED',
  AUTH_GEN_FAILED = 'AUTH_GEN_FAILED',

  // Auth polling
  AUTH_POLL_HTTP_FAILED = 'AUTH_POLL_HTTP_FAILED',
  AUTH_POLL_PARSE_FAILED = 'AUTH_POLL_PARSE_FAILED',
  AUTH_REJECTED = 'AUTH_REJECTED',
  AUTH_TIMEOUT = 'AUTH_TIMEOUT',

  // Auth session
  AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND',

  // Binding
  BINDING_NOT_FOUND = 'BINDING_NOT_FOUND',

  // Query
  QUERY_PARSE_FAILED = 'QUERY_PARSE_FAILED',
  QUERY_DAILY_LIMIT = 'QUERY_DAILY_LIMIT',
  QUERY_FAILED = 'QUERY_FAILED'
}
